#!/bin/bash
mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE DATABASE IF NOT EXISTS wiki CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'wikiuser'@'%' IDENTIFIED BY '${WIKI_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON wiki.* TO 'wikiuser'@'%';

CREATE DATABASE IF NOT EXISTS casdoor CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'casdoor'@'%' IDENTIFIED BY '${CASDOOR_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON casdoor.* TO 'casdoor'@'%';

FLUSH PRIVILEGES;
EOF