<?php
# This file was automatically generated by the MediaWiki 1.42.7
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "SOURCE DCS WIKI";
$wgMetaNamespace = "SOURCE_DCS_WIKI";
## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki.sourcedcs.page";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "https://sourcedcs.page/sourcelogobg.png",
	'icon' => "https://sourcedcs.page/sourcelogobg.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mariadb";
$wgDBname = "wiki";
$wgDBuser = "wikiuser";
$wgDBpassword = "79PSCr5CRmxLbGXNT2Ji";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "ae9903c8272fbfcaff5f6b0ca20053a60abec69f6a6e420d9b187f3982edce2e";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a63571451e51c311";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";


## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
wfLoadSkin('Citizen');
$wgDefaultSkin = 'citizen';
$wgCitizenThemeDefault = 'light';

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'Cite' );

$wgUseSiteCss = true;
$wgAllowSiteCSSOnRestrictedPages = true;

$wgUsePrivateIPs = true;
$wgPasswordAttemptThrottle = [];

# End of automatically generated settings.
# Add more configuration options below.
// Pluggable Auth + Casdoor OIDC
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'OpenIDConnect' );

$wgPluggableAuth_Config = [
    'Log in with Discord' => [
        'plugin' => 'OpenIDConnect',
        'data' => [
            'providerURL'  => 'https://auth.sourcedcs.page',
            'clientID'     => 'bd11a08604f091824ea0',
            'clientSecret' => '9fb0379ec19a72bb0eb877861865c8ee6d43e2ba',
            'redirectUri'  => 'https://wiki.sourcedcs.page/index.php/Special:PluggableAuthLogin',
            'responseType' => 'code',
            'scope'        => ['openid', 'profile', 'email'],
        ]
    ]
];

$wgGroupPermissions['*']['createaccount'] = true;
$wgPluggableAuth_EnableAutoLogin  = false;
$wgPluggableAuth_EnableLocalLogin = false;

$wgGroupPermissions['*']['edit']    = false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['user']['read'] = true;

$wgGroupPermissions['member']['read']      = true;
$wgGroupPermissions['pilot']['read']       = true;
$wgGroupPermissions['elementlead']['read'] = true;

$wgGroupPermissions['flightlead']['read']       = true;
$wgGroupPermissions['flightlead']['edit']       = true;
$wgGroupPermissions['flightlead']['createpage'] = false;

$wgGroupPermissions['squadronlead']['read']       = true;
$wgGroupPermissions['squadronlead']['edit']       = true;
$wgGroupPermissions['squadronlead']['createpage'] = true;

$wgGroupPermissions['admin']['read']          = true;
$wgGroupPermissions['admin']['edit']          = true;
$wgGroupPermissions['admin']['createpage']    = true;
$wgGroupPermissions['admin']['delete']        = true;
$wgGroupPermissions['admin']['protect']       = true;
$wgGroupPermissions['admin']['editinterface'] = true;
$wgGroupPermissions['admin']['editsitecss']   = true;
$wgGroupPermissions['admin']['editsitejs']    = true;

$wgOpenIDConnect_MigrateUsersByUserName = true;

wfLoadExtension( 'CasdoorSync' );
$wgCasdoorSyncClientId     = 'bd11a08604f091824ea0';
$wgCasdoorSyncClientSecret = '9fb0379ec19a72bb0eb877861865c8ee6d43e2ba';
$wgCasdoorSyncBaseUrl      = 'https://auth.sourcedcs.page';
$wgJobRunRate = 0;


$wgDebugLogFile = '/tmp/mediawiki-debug.log';
$wgDebugLogGroups['OpenIDConnect'] = '/tmp/oidc-debug.log';
